### ISSUE TITLE
Transparent Lotties not rendering correctly

### ISSUE THREAD

**Issue by weblot** [GrandMastersOnline/obs-lottie#2]
First, thank you for making the windows version! I am having an issue displaying Lottie files that have transparent sections. They work fine if I use a Browser source, but the plugin doesn't render it the same. I'm using OBS 28 on a Windows machine. 

Here is a screenshot of the Lottie in a Browser Source:
https://drive.google.com/file/d/1Qx2KChLjwlO9MJN8a9VidjjHH4sKy6OF/view?usp=sharing

The same Lottie inside the plugin:
https://drive.google.com/file/d/1AHiEeFUUg-INp7nLhY1JL8crQFPnqeP2/view?usp=sharing

A link to the Lottie file:
https://drive.google.com/file/d/1-nNx0kHsI16U62JzDNGx_9rToHdqMJly/view?usp=sharing

**Comment by zyzniewski** [comment]
Hi, OBS-Lottie plugin is using [rlottie](https://github.com/Samsung/rlottie) library under the hood for rendering.
Seems like you're using one of the non-supported effect: https://github.com/Samsung/rlottie#supported-after-effects-features

Unfortunately, there's nothing I can do about it right now.
A possible solution for the future: change the underlying rendering library - [glottie](https://github.com/LottieFiles/glottie) but it also seems to be a WIP:
> Glottie is currently still under development and does not support all the features of the lottie format

**Comment by weblot** [comment]
No problem! Thanks for messaging me back. I will take a look at rlottie. Thank you again for making this plugin!
