### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by mandrachek** [GrandMastersOnline/obs-lottie#3]
Can you provide an apple silicon build?

**Comment by zyzniewski** [comment]
rlottie (underlying library) has some problems with building on arm64 https://github.com/Samsung/rlottie/issues/496

**Comment by zyzniewski** [comment]
Hi @mandrachek I've applied unofficial patch for Apple Silicon, can you give it a try https://github.com/GrandMastersOnline/obs-lottie/releases/tag/v1.0.2
