### ISSUE TITLE
[Feature Request] Restart playback when source becomes active, loop and show nothing when playback ends

### ISSUE THREAD

**Issue by andrewcartwright1** [GrandMastersOnline/obs-lottie#4]
Hey,

Just wondering If it would be possible to add the following settings?

![image](https://user-images.githubusercontent.com/10059155/229354577-51a32f30-d1c8-4d52-b673-11c3ffc3d3d2.png)

I'm currently using this and was thinking of adding some confetti style animations using lottie but noticed while playing about with it sometimes it will show an already in progress animation, realized its because its not restarting.

Thank you very much, and great addon!

**Comment by zyzniewski** [comment]
Hi, check out the new release: https://github.com/GrandMastersOnline/obs-lottie/releases

**Comment by andrewcartwright1** [comment]
Thank you so much! :D
